Add git warning
Signed-off-by: Nicolae Dicu <n.dicu@eco.sensified.de>

diff --git a/.github/actions/gitlint/action.yml b/.github/actions/gitlint/action.yml
--- a/.github/actions/gitlint/action.yml
+++ b/.github/actions/gitlint/action.yml
@@ -31,4 +31,11 @@ runs:
       git config --global --add safe.directory /github/workspace && \
       git fetch origin +refs/heads/main:refs/remotes/origin/main && \
       git fetch origin +refs/pull/${{ inputs.pr-number }}/head && \
-      gitlint --commits origin/main..HEAD
+      if ! gitlint --commits origin/main..HEAD; then \
+        echo "WARNING: Your commit message does not follow the required format."
+        echo "To fix your commit message, run:"
+        echo " git commit --amend"
+        echo "Then update your commit (fix gitlint warnings). Finally, force-push:"
+        echo " git push --force-with-lease"
+        exit 1; \
+      fi
